// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9cU8bxjsXS9jDGE5nSX0bkgEGFyFBYPY',
    appId: '1:994395131462:web:7fb766b30d0029ff750447',
    messagingSenderId: '994395131462',
    projectId: 'e-ticaret-919d7',
    authDomain: 'e-ticaret-919d7.firebaseapp.com',
    storageBucket: 'e-ticaret-919d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl89VH8reGJdSBKCfB_yKf6qXKiYolo00',
    appId: '1:994395131462:android:1a565789c349601a750447',
    messagingSenderId: '994395131462',
    projectId: 'e-ticaret-919d7',
    storageBucket: 'e-ticaret-919d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNGMv-jcWZCd8evyiojcl-pcXHpel3vHY',
    appId: '1:994395131462:ios:a4eeda90ad091043750447',
    messagingSenderId: '994395131462',
    projectId: 'e-ticaret-919d7',
    storageBucket: 'e-ticaret-919d7.appspot.com',
    iosClientId: '994395131462-43n0h3otpc6f71fjf07okg7mf97cqk3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.eTicaretApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNGMv-jcWZCd8evyiojcl-pcXHpel3vHY',
    appId: '1:994395131462:ios:a4eeda90ad091043750447',
    messagingSenderId: '994395131462',
    projectId: 'e-ticaret-919d7',
    storageBucket: 'e-ticaret-919d7.appspot.com',
    iosClientId: '994395131462-43n0h3otpc6f71fjf07okg7mf97cqk3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.eTicaretApp',
  );
}
